import { TopicModel } from './TopicModel';

export default function seed() {
  TopicModel.find({}).remove(function(){
    TopicModel.create([
      {
        "datePosted":new Date("4/6/2016 11:22"),
        "dateScheduled":"4-May-2016",
        "speakerName":"Ritesh Batra",
        "speakerId":70861,
        "speakerEmail":"rbatra@sapient.com",
        "speakerMobile":9899891122,
        "location":"Noida",
        "domain":"Interactive Development",
        "description":"This talks about the new dimensions of Interactive development and how to resolve integration pain points for XT dev's",
        "title":"Hybris First Approach.",
        "comments":"",
        "event": "XT Summit",
        "status": 1,
        "upVotes": 0
      },
      {
        "datePosted":new Date("4/6/2016 11:28"),
        "dateScheduled":"4-May-2016",
        "speakerName":"Shafeeq Ur Rahman",
        "speakerId":109806,
        "speakerEmail":"srahman2@sapient.com",
        "speakerMobile":7795251713,
        "location":"Bangalore",
        "domain":"PWA",
        "description":"What else should happen when we don't have Internet connectivity?",
        "title":"Offline Apps with React",
        "comments":"",
        "event": "XT Summit",
        "status": 1,
        "upVotes": 0
      },
      {
        "datePosted":new Date("4/6/2016 17:53"),
        "dateScheduled":"4-May-2016",
        "speakerName":"Priya Bhatt",
        "speakerId":114963,
        "speakerEmail":"pbhatt@sapient.com",
        "speakerMobile":8792185479,
        "location":"Bangalore",
        "domain":"Interactive Development",
        "description":"The talk is all about a game changing template engine which is straight out Ebay called Marko. Which is a high performance templating engine which has feature of streaming output, asynchronous render blocks, isomorphically rendered, support of custom tags and individual controllers with minimal memory footprint.",
        "title":"High performance HTML-based templating engine",
        "comments":"",
        "event": "XT Summit",
        "status": 1,
        "upVotes": 0
      },
      {
        "datePosted":new Date("4/7/2016 3:21"),
        "dateScheduled":"4-May-2016",
        "speakerName":"Arihant Verma",
        "speakerId":114736,
        "speakerEmail":"averma51@sapient.com",
        "speakerMobile":9901073059,
        "location":"Bangalore",
        "domain":"Reactive Web Architecture",
        "description":"What else people would get to know about Full Stack Ecosystem: Built in Reactive Programming right up to the database. ",
        "title":"Introduction to Meteor Framework (and a little beyond)",
        "comments":"",
        "event": "XT Summit",
        "status": 1,
        "upVotes": 0
      },
      {
        "datePosted":new Date("4/9/2016 8:56"),
        "dateScheduled":"4-May-2016",
        "speakerName":"Akhouri Anand kumar",
        "speakerId":69216,
        "speakerEmail":"akumar69@sapient.com",
        "speakerMobile":9811160802,
        "location":"Noida",
        "domain":"Augmented Reality",
        "description":"Marketing And Advertising on News paper then Radio then Tv then Web then mobile \"What Else\" Feel Marketing And Advertising by Augmented Reality.",
        "title":"Augmented Reality - Next Generation Tool",
        "comments":"",
        "event": "XT Summit",
        "status": 1,
        "upVotes": 0
      },
      {
        "datePosted":new Date("4/11/2016 13:02"),
        "dateScheduled":"4-May-2016",
        "speakerName":"Chiragkumar Kanjibhai Rupani",
        "speakerId":118068,
        "speakerEmail":"crupani@sapient.com",
        "speakerMobile":9503535016,
        "location":"Bangalore",
        "domain":"Reactive Web Architecture",
        "description":"Most software today deals with data that's available only over time: Websites load remote resources and respond to complex user interactions, servers are distributed across multiple physical locations, and people have mobile devices that they expect to work at all times, whether on high-speed Wi-Fi or spotty cellular networks. Any serious application involves many moving asynchronous parts that need to be efficiently coordinated, and that�s very hard with today�s programming techniques. On top of that, we have what�s always been there: servers crashing, slow networks, and software bugs we have to deal with. �What else� will be a reactive way of doing programming. Reactive programming allows us to build event-driven, resilient and more responsive websites.",
        "title":"Reactive Programming with RxJS",
        "comments":"NA",
        "event": "XT Summit",
        "status": 1,
        "upVotes": 0
      },
      {
        "datePosted":new Date("4/11/2016 15:24"),
        "dateScheduled":"4-May-2016",
        "speakerName":"Vidhya Vijai Anand",
        "speakerId":117849,
        "speakerEmail":"vanand7@sapient.com",
        "speakerMobile":9500095536,
        "location":"Bangalore",
        "domain":"Interactive Development",
        "description":"Style Guide Driven Development lays the groundwork for building more scalable and maintainable applications while providing a common place for communicating among developers, designers, and stakeholders. ",
        "title":"Style Guide Driven Development",
        "comments":"This topic will create a spark in the way designers, developers and stakeholders are thinking about the prototypes.",
        "event": "XT Summit",
        "status": 1,
        "upVotes": 0
      },
      {
        "datePosted":new Date("4/11/2016 18:05"),
        "dateScheduled":"4-May-2016",
        "speakerName":"Suvarna Mondal",
        "speakerId":109810,
        "speakerEmail":"smondal2@sapient.com",
        "speakerMobile":9066580946,
        "location":"Bangalore",
        "domain":"Interactive Development",
        "description":"Unit testing is an important step in the development workflow. This talk covers the ins and outs of front end testing and how important it is for the maintainability of a project",
        "title":"Writing Testable javascript",
        "comments":"",
        "event": "XT Summit",
        "status": 1,
        "upVotes": 0
      },
      {
        "datePosted":new Date("4/12/2016 8:27"),
        "dateScheduled":"4-May-2016",
        "speakerName":"Visweshwaran Suryanarayanan ",
        "speakerId":114959,
        "speakerEmail":"Vsuryanarayanan@sapient.com",
        "speakerMobile":9790786094,
        "location":"Bangalore",
        "domain":"Open source",
        "description":"Machine intensive functionalities in full stack ",
        "title":"Go! ",
        "comments":"",
        "event": "XT Summit",
        "status": 1,
        "upVotes": 0
      },
      {
        "datePosted":new Date("4/12/2016 12:19"),
        "dateScheduled":"4-May-2016",
        "speakerName":"Aayushi",
        "speakerId":111079,
        "speakerEmail":"anarula2@sapient.com",
        "speakerMobile":9818446941,
        "location":"Gurgaon",
        "domain":"Interactive Development",
        "description":"What else will change the way look at Interactive Development opportunities inside Demandware Platform.",
        "title":"Know Demandware",
        "comments":"",
        "event": "XT Summit",
        "status": 1,
        "upVotes": 0
      },
      {
        "datePosted":new Date("4/12/2016 12:26"),
        "dateScheduled":"4-May-2016",
        "speakerName":"Hari Karthic Mahadevan",
        "speakerId":110757,
        "speakerEmail":"hmahadevan@sapient.com",
        "speakerMobile":9535539776,
        "location":"Bangalore",
        "domain":"Virtual Reality",
        "description":"What else can we, as Interactive developers, look forward to in the coming years ? The tech landscape is changing at a rapid pace and along with it the way end users interact with tech . With the release of solid  VR and AR hardware , this might be the next big break in the Human computer Interaction since WWW. The presentation is an attempt to pique the collective interest of Devs and make them  turn their  heads away from React/Node for a moment and look at VR /AR :)",
        "title":"Unity VR- A Primer",
        "comments":"",
        "event": "XT Summit",
        "status": 1,
        "upVotes": 0
      },
      {
        "datePosted":new Date("4/12/2016 12:57"),
        "dateScheduled":"4-May-2016",
        "speakerName":"Harish K U",
        "speakerId":109843,
        "speakerEmail":"hkuluruliya@sapient.com",
        "speakerMobile":9945507643,
        "location":"Bangalore",
        "domain":"Machine Learning",
        "description":"What else can one use to stretch the boundaries of ML? Can we leverage the power of node.js to come up with new implementations of ML algorithms? How about a host of ML libraries available as a npm package? This presentation aims to shine a light on some of the existing libraries and also what's in store for the future. ",
        "title":"Machine Learning in JavaScript",
        "comments":"",
        "event": "XT Summit",
        "status": 1,
        "upVotes": 0
      },
      {
        "datePosted":new Date("4/12/2016 14:55"),
        "dateScheduled":"4-May-2016",
        "speakerName":"Rahul Ram Sheela",
        "speakerId":105241,
        "speakerEmail":"rsheela@sapient.com",
        "speakerMobile":9902163545,
        "location":"Bangalore",
        "domain":"Interactive Development",
        "description":"Static site generator for Node.js, Grunt.js, and Yeoman and Gulp. Can render templates with Handlebars, Lo-Dash or any template engine.",
        "title":"Assemble - Static site generator",
        "comments":"Adding Saravana Gopal (ID: sgopal) and Venkatachalam Subramani (ID : vsubr2) in the team",
        "event": "XT Summit",
        "status": 1,
        "upVotes": 0
      },
      {
        "datePosted":new Date("4/12/2016 15:51"),
        "dateScheduled":"4-May-2016",
        "speakerName":"Jagadeesh",
        "speakerId":110087,
        "speakerEmail":"jjayachandran2@sapient.com",
        "speakerMobile":8884268723,
        "location":"Bangalore",
        "domain":"Interactive Development",
        "description":"Gesture recognition is not common in recent days. This is a small effort to make the browsers recognising the gestures and make them intelligent",
        "title":"Gesture Recognition for Browsers",
        "comments":"",
        "event": "XT Summit",
        "status": 1,
        "upVotes": 0
      },
      {
        "datePosted":new Date("4/12/2016 17:29"),
        "dateScheduled":"4-May-2016",
        "speakerName":"Sahil Tandon",
        "speakerId":112301,
        "speakerEmail":"standon4@sapient.com",
        "speakerMobile":9535682681,
        "location":"Bangalore",
        "domain":"Interactive Development",
        "description":"What else can we achieve with JavaScript in the field of 3D Computer Graphics and Animation",
        "title":"Game Development using three.js",
        "comments":"",
        "event": "XT Summit",
        "status": 1,
        "upVotes": 0
      },
      {
        "datePosted":new Date("4/12/2016 18:08"),
        "dateScheduled":"4-May-2016",
        "speakerName":"Mayank Jain",
        "speakerId":111084,
        "speakerEmail":"mjain28@sapient.com",
        "speakerMobile":9650419555,
        "location":"Gurgaon",
        "domain":"Machine Learning",
        "description":"can computer learn creativity",
        "title":"Machine Learning for everyday experinces",
        "comments":"",
        "event": "XT Summit",
        "status": 1,
        "upVotes": 0
      },
      {
        "datePosted":new Date("4/12/2016 20:25"),
        "dateScheduled":"4-May-2016",
        "speakerName":"Chetan Keshav",
        "speakerId":109862,
        "speakerEmail":"ckeshav@sapient.com",
        "speakerMobile":9620350278,
        "location":"Bangalore",
        "domain":"Interactive Development",
        "description":"Although CSS animations have done a good job at replacing Flash based animations, they're still pretty complicated. Greensock makes the process easy.",
        "title":"Greensock : Animation of web made easy",
        "comments":"",
        "event": "XT Summit",
        "status": 1,
        "upVotes": 0
      },
      {
        "datePosted":new Date("4/12/2016 21:47"),
        "dateScheduled":"4-May-2016",
        "speakerName":"Rakesh Menon",
        "speakerId":112083,
        "speakerEmail":"rmenon3@sapient.com",
        "speakerMobile":9811107220,
        "location":"Gurgaon",
        "domain":"Interactive Development",
        "description":"What else will change the way we code for User Interface elements.\n\nReactive programming is programming with asynchronous data streams. Data streams can be anything like events, variables, user inputs, properties, caches, data structures etc. It's a sequence of events ordered in time can emit either a value, error or completed. We'll look at how we can make use of the functional utilities like map, filter, scan etc. in RxJS to create and process these data streams and dive into a new paradigm. Observer Design Pattern on steroids.",
        "title":"Functional Reactive Programming in JavaScript (with RxJS)",
        "comments":"",
        "event": "XT Summit",
        "status": 1,
        "upVotes": 0
      },
      {
        "datePosted":new Date("4/13/2016 3:04"),
        "dateScheduled":"4-May-2016",
        "speakerName":"Pawan gangwani",
        "speakerId":117847,
        "speakerEmail":"pgangwani2@sapient.com",
        "speakerMobile":7387874848,
        "location":"Bangalore",
        "domain":"Interactive Development",
        "description":"I would like to brief about the topic and then demonstrate how it can be used with angular world.",
        "title":"Functional Reactive Programming",
        "comments":"",
        "event": "XT Summit",
        "status": 1,
        "upVotes": 0
      },
      {
        "datePosted":new Date("4/13/2016 3:08"),
        "dateScheduled":"4-May-2016",
        "speakerName":"Pawan Gangwani",
        "speakerId":117847,
        "speakerEmail":"pgangwani2@sapient.com",
        "speakerMobile":7387874848,
        "location":"Bangalore",
        "domain":"Interactive Development",
        "description":"I am thinking to develop small tool based on my below link of vox so that I can showcase the ideas and the next steps for it.",
        "title":"Cross browser creative testing automation",
        "comments":"I would need some mobile phone tablets to demonstrate this. May be exact requirement may vary for them based on my preparation.",
        "event": "XT Summit",
        "status": 1,
        "upVotes": 0
      },
      {
        "datePosted":new Date("4/13/2016 12:11"),
        "dateScheduled":"4-May-2016",
        "speakerName":"Sreevidya",
        "speakerId":118382,
        "speakerEmail":"sjayanthi@sapient.com",
        "speakerMobile":9620685556,
        "location":"Bangalore",
        "domain":"Interactive Development",
        "description":"WebGL helps to perform 3D rendering of HTML canvas element. WebGL allows to use API based on openGL. We can have special effect code which will be executed in GPU",
        "title":"WebGL",
        "comments":"",
        "event": "XT Summit",
        "status": 1,
        "upVotes": 0
      },
      {
        "datePosted":new Date("4/13/2016 14:18"),
        "dateScheduled":"4-May-2016",
        "speakerName":"Anup Mankar",
        "speakerId":108177,
        "speakerEmail":"amankar@sapient.com",
        "speakerMobile":9483503092,
        "location":"Bangalore",
        "domain":"Interactive Development",
        "description":"What if browsers could allow you to extend the power of CSS? Have we imagined the world of web development where we would not be bound by the browser's out of the box capability? We take a look at the proceedings of the CSS TAG's Houdini Task Force, which is defining the rules for the next level of extensible web.",
        "title":"Project Houdini",
        "comments":"",
        "event": "XT Summit",
        "status": 1,
        "upVotes": 0
      },
      {
        "datePosted":new Date("4/13/2016 15:13"),
        "dateScheduled":"4-May-2016",
        "speakerName":"Parthiban",
        "speakerId":109999,
        "speakerEmail":"pnatarajan@sapient.com",
        "speakerMobile":9916458008,
        "location":"Bangalore",
        "domain":"Reactive Web Architecture",
        "description":"How the Angular developer can quickly understand the react and what kind of difference from angular to React",
        "title":"Make the React from Angular",
        "comments":"",
        "event": "XT Summit",
        "status": 1,
        "upVotes": 0
      },
      {
        "datePosted":new Date("4/13/2016 18:58"),
        "dateScheduled":"4-May-2016",
        "speakerName":"Manish Shekhawat",
        "speakerId":108631,
        "speakerEmail":"mshekhawat@sapient.com",
        "speakerMobile":8800605544,
        "location":"Gurgaon",
        "domain":"User Experience",
        "description":"Give a perspective on how exactly does the browser go from consuming our HTML, CSS, and JavaScript to rendered pixels on the screen.",
        "title":"Is Critical Rendering Path Critical?",
        "comments":"",
        "event": "XT Summit",
        "status": 1,
        "upVotes": 0
      },
      {
        "datePosted":new Date("4/13/2016 22:47"),
        "dateScheduled":"4-May-2016",
        "speakerName":"Sudhanshu Srivastava",
        "speakerId":115569,
        "speakerEmail":"ssrivastava49@sapient.com",
        "speakerMobile":9910058414,
        "location":"Noida",
        "domain":"Interactive Development",
        "description":"Problem: In the JavaScript programming model, the de-facto standard of asynchronous programming is through using callbacks. Whilst this may work fine for a single AJAX request, we quickly run into problem when there is a lot of asynchrony involved. This is the most common problem in a Node app and is commonly referred to as �Callback hell�, resulting in some major headaches in legibility and exceptions.\n\nSolution: With the evolution of technology many solutions / frameworks have been proposed to solve the callback hell, however many of them are at best hacks or cobbled up solutions and do not enjoy native support from the Javascript engine. \n\nUntil now�\n\nWith the advent of ES6 generators not only we have the most elegant solution for callback hell, they are baked right into the JS engine and any framework can take advantage of it. Taking advantage of generators is Koa framework brought to you by authors of express (the most popular framework for Node).\n\nWith this flash talk I aim to introduce the problem and various solutions of callback hell before introducing the Koa framework and explaining its advantage.",
        "title":"Generators and the Next Gen Framework",
        "comments":"",
        "event": "XT Summit",
        "status": 1,
        "upVotes": 0
      },
      {
        "datePosted":new Date("4/14/2016 11:37"),
        "dateScheduled":"4-May-2016",
        "speakerName":"Sajan",
        "speakerId":96173,
        "speakerEmail":"sajanjohn@gmail.com",
        "speakerMobile":9980162129,
        "location":"Bangalore",
        "domain":"IoT",
        "description":"Quick presentation and demo on how to build your own Amazon echo using Raspberry Pi and Amazon API",
        "title":"Create your own Alexa",
        "comments":"",
        "event": "XT Summit",
        "status": 1,
        "upVotes": 0
      },
      {
        "datePosted":new Date("4/14/2016 11:46"),
        "dateScheduled":"4-May-2016",
        "speakerName":"Amalan George William",
        "speakerId":71101,
        "speakerEmail":"awilliam@sapient.com",
        "speakerMobile":9741126634,
        "location":"Bangalore",
        "domain":"UI testing tool",
        "description":"just want to present the tool which i have created to support the UI development and testing, Creative QA.",
        "title":"Page tester - A UI Testing tool",
        "comments":"",
        "event": "XT Summit",
        "status": 1,
        "upVotes": 0
      },
      {
        "datePosted":new Date("4/14/2016 11:48"),
        "dateScheduled":"4-May-2016",
        "speakerName":"Subin Paul",
        "speakerId":87295,
        "speakerEmail":"spaul3@sapient.com",
        "speakerMobile":9900828586,
        "location":"Bangalore",
        "domain":"Interactive Development",
        "description":"Present & future of media in web. (content is yet to be finalized)",
        "title":"Media in Modern web",
        "comments":"",
        "event": "XT Summit",
        "status": 1,
        "upVotes": 0
      },
      {
        "datePosted":new Date("4/14/2016 11:54"),
        "dateScheduled":"4-May-2016",
        "speakerName":"Rajat Chhillar",
        "speakerId":117394,
        "speakerEmail":"rchhillar@sapient.com",
        "speakerMobile":7065248006,
        "location":"Gurgaon",
        "domain":"Freedom of speech gone too far",
        "description":"what does freedom of speech means and how people perceive it, is there any difference?",
        "title":"Freedom of speech gone too far?",
        "comments":"",
        "event": "XT Summit",
        "status": 1,
        "upVotes": 0
      },
      {
        "datePosted":new Date("4/14/2016 12:14"),
        "dateScheduled":"4-May-2016",
        "speakerName":"Durga Etamsetty",
        "speakerId":119511,
        "speakerEmail":"detamsetty@sapient.com",
        "speakerMobile":9901377831,
        "location":"Bangalore",
        "domain":"IoT",
        "description":"IOT and its impacts on peoples life",
        "title":"IOT",
        "comments":"",
        "event": "XT Summit",
        "status": 1,
        "upVotes": 0
      },
      {
        "datePosted":new Date("4/14/2016 13:44"),
        "dateScheduled":"4-May-2016",
        "speakerName":"Nisheed Jagadish",
        "speakerId":102248,
        "speakerEmail":"njagadish3@gmail.com",
        "speakerMobile":9740099771,
        "location":"Bangalore",
        "domain":"Interactive Development",
        "description":"What else will change the way we interact with applications, people and the world",
        "title":"Future of E-commerce and Immersive Experiences",
        "comments":"Would love any suggestions.",
        "event": "XT Summit",
        "status": 1,
        "upVotes": 0
      },
      {
        "datePosted":new Date("4/14/2016 14:10"),
        "dateScheduled":"4-May-2016",
        "speakerName":"Nisheed Jagadish",
        "speakerId":102248,
        "speakerEmail":"njagadish3@sapient.com",
        "speakerMobile":9740099771,
        "location":"Bangalore",
        "domain":"Interactive Development",
        "description":"We have seen gulp grunt jenkins and couple of other build tools. Lets look into what else this modern module bundler help us do. This would include best practices and production concerns.",
        "title":"Webpack and it's uses for development",
        "comments":"",
        "event": "XT Summit",
        "status": 1,
        "upVotes": 0
      },
      {
        "datePosted":new Date("4/14/2016 14:30"),
        "dateScheduled":"4-May-2016",
        "speakerName":"Yoganandh Durvasulu",
        "speakerId":107157,
        "speakerEmail":"ydurvasulu@sapient.com",
        "speakerMobile":9972229452,
        "location":"Bangalore",
        "domain":"Interactive Development",
        "description":"Guide to become a full stack developer in 10 mins.",
        "title":"Step-in to Full stack",
        "comments":"NO",
        "event": "XT Summit",
        "status": 1,
        "upVotes": 0
      },
      {
        "datePosted":new Date("4/14/2016 15:01"),
        "dateScheduled":"4-May-2016",
        "speakerName":"Bhumika Sharma ",
        "speakerId":72130,
        "speakerEmail":"Bsharma3@sapient.com",
        "speakerMobile":9880366744,
        "location":"Bangalore",
        "domain":"Social Media- the what else part",
        "description":"Social Media- the what else part",
        "title":"Social Media- the what else part",
        "comments":"",
        "event": "XT Summit",
        "status": 1,
        "upVotes": 0
      },
      {
        "datePosted":new Date("4/14/2016 16:38"),
        "dateScheduled":"4-May-2016",
        "speakerName":"SHOURYA RANKA",
        "speakerId":112262,
        "speakerEmail":"sranka.2310@gmail.com",
        "speakerMobile":9717083599,
        "location":"Gurgaon",
        "domain":"Interactive Development",
        "description":"Demonstrate how use of Data Structures and Algorithms which are generally associated to programming languages and not scripting languages can help better optimize coding in JavaScript. We will walk through a few code snippets and how these algorithms hold significance with the web",
        "title":"Data Structures and Algorithms in JavaScript",
        "comments":"Code Snippets and Algorithms Statistics will be presented through a presentation. ",
        "event": "XT Summit",
        "status": 1,
        "upVotes": 0
      },
      {
        "datePosted":new Date("4/14/2016 20:01"),
        "dateScheduled":"4-May-2016",
        "speakerName":"Subhasree Murugan",
        "speakerId":112322,
        "speakerEmail":"smurugan@sapient.com",
        "speakerMobile":9108555060,
        "location":"Bangalore",
        "domain":"Interactive Development",
        "description":"Gigantic mounts of data are being generated on a daily basis. The amount of data being generated is growing exponentially every year. The ability to understand and extract value from data is hugely easier when done through a Data Visualization rather than from looking at the raw data or the simple statistics of the data.thus D3.Js is one library which can be used by developers to create the charts. ",
        "title":"Data Visualization with D3.js",
        "comments":"",
        "event": "XT Summit",
        "status": 1,
        "upVotes": 0
      },
      {
        "datePosted":new Date("4/15/2016 9:19"),
        "dateScheduled":"4-May-2016",
        "speakerName":"Santhosh Sundar",
        "speakerId":100775,
        "speakerEmail":"ssundar3@sapient.com",
        "speakerMobile":9845439468,
        "location":"Bangalore",
        "domain":"Machine Learning",
        "description":"JavaScript has come a long way, from being just limited to browsers, to joining the \"write once, run anywhere\" club, there has been a leap in how JS has been changing the world. What else can we do with JS that takes us further deep? So deep that it can eventually explore the world of Neural Network? Machine Learning in JavaScript could help us explore the unknown, change the way how users interact with web, devices, things around us and ease the decision-making process. The future is ruled by machines!",
        "title":"Machine Learning in JavaScript",
        "comments":"I do not have a PoC yet. This talk will be a detailed introduction on Machine Learning in JavaScript. I would try to get a PoC done, but considering the timeline, the chances are a little bleak. I shall try though! :)",
        "event": "XT Summit",
        "status": 1,
        "upVotes": 0
      },
      {
        "datePosted":new Date("4/15/2016 10:44"),
        "dateScheduled":"4-May-2016",
        "speakerName":"K S Rahul",
        "speakerId":109840,
        "speakerEmail":"krahul@sapient.com",
        "speakerMobile":9902709574,
        "location":"Bangalore",
        "domain":"IoT",
        "description":"Its a hardware and software demo. The sensor readings from hardware will be streamed online and based on the condition written in our node js app any action can be taken like push notifications in mobile phones, SMS, Twitter notification etc. It uses mqtt pub/sub protocol which handles device to device communication efficiently. The IoT app will be cloud hosted on Bluemix IBM server. This is a demo showcasing the endless possibilities but imagine if your alarm can adjust if your train/flight is delayed, send notification when the dam water level has risen above critical level etc.",
        "title":"Cloud hosted IoT app with mqtt and nodejs ",
        "comments":"",
        "event": "XT Summit",
        "status": 1,
        "upVotes": 0
      },
      {
        "datePosted":new Date("4/15/2016 14:34"),
        "dateScheduled":"4-May-2016",
        "speakerName":"Rajeev roushan sharma",
        "speakerId":99722,
        "speakerEmail":"rsharma55@sapient.com",
        "speakerMobile":8102226932,
        "location":"Gurgaon",
        "domain":"IoT",
        "description":"iCart is a simple shopping cart with some kind of smart device which Prompts user of any kind of store promotion based of items in the shopping cart",
        "title":"iCart",
        "comments":"",
        "event": "XT Summit",
        "status": 1,
        "upVotes": 0
      },
      {
        "datePosted":new Date("4/15/2016 16:22"),
        "dateScheduled":"4-May-2016",
        "speakerName":"Ram Murat Sharma",
        "speakerId":104495,
        "speakerEmail":"rsharma68@sapient.com",
        "speakerMobile":8802990458,
        "location":"Gurgaon",
        "domain":"User Experience",
        "description":"GIDS installation walk-through  ",
        "title":"Build your story",
        "comments":"",
        "event": "XT Summit",
        "status": 1,
        "upVotes": 0
      },{
        "datePosted":new Date("4/13/2016  4:42"),
        "dateScheduled":"4-May-2016",
        "speakerName":"Jithin Nair, Onkar Bulbule",
        "speakerId":112303,
        "speakerEmail":"rsharma68@sapient.com",
        "speakerMobile":8971029166,
        "location":"Bangalore",
        "domain":"User Experience",
        "description":"What else will combine UX Design with Innovation and Technology? Google's new design philosophy, where the technology is inspired by paper and ink, that is utilized to facilitate creativity and innovation to introduce users to a new design language. In the course of the presentation, we'll also see how Materialize enables us to bring the innovation of Material Design into web development.",
        "title":"Materialize with Material Design",
        "comments":"",
        "event": "XT Summit",
        "status": 1,
        "upVotes": 0
      },{
        "datePosted":new Date("4/12/2016  5:54"),
        "dateScheduled":"4-May-2016",
        "speakerName":"Divya Virmani, Alisha Singla",
        "speakerId":109745,
        "speakerEmail":"dvirmani2@sapient.com",
        "speakerMobile":7838929337,
        "location":"Gurgaon",
        "domain":"Sapient : My First Company",
        "description":"\"How working in your first company has driven the course of your life?\" \"How was it like working as a fresher in Sapient? \"Well, through this presentation we aim to showcase how your first company lays foundation of your interests. \"And how are we going to do this?\" Storyscaping the experience of landing straight away from a college comfort zone to a challenging workstation!",
        "title":"Sapient : My First Company",
        "comments":"",
        "event": "XT Summit",
        "status": 1,
        "upVotes": 0
      }
    ])
  });
}
